version: '3.8'

services:
  # MongoDB數據庫服務
  mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/google_containers/mongo:latest
    container_name: vuln-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-vulnmanagement}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - vuln-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/vulnmanagement --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 後端服務
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuln-backend
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password}@mongodb:27017/${MONGO_DATABASE:-vulnmanagement}?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key}
      PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - vuln-network

  # 前端服務
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vuln-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - vuln-network

# 數據卷
volumes:
  mongodb_data:
    driver: local

# 網絡
networks:
  vuln-network:
    driver: bridge 